# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170625_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
