# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170626_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default="--father's name of student--", help_text='Format: (Last Name, First Name, Middle Name)', max_length=120, verbose_name="father's name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default='name of student guardian', help_text='Full name of guardian', max_length=160, verbose_name="guardian's name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default="--mother's name of student--", help_text='Format: (Last Name, First Name, Middle Name)', max_length=120, verbose_name="mother's name"),
        ),
    ]
