# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
