# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='form_name',
            field=models.CharField(default='School Form 1', max_length=60, unique=True),
        ),
    ]
