# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolforms', '0002_schoolform_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolform',
            name='form_name',
            field=models.CharField(default='School Form 1', max_length=60),
        ),
    ]
